### ISSUE TITLE
Java base image for Apple Silicon

### ISSUE THREAD

**Issue by toresbe** [navikt/baseimages#128]
Stadig flere utviklere bruker macs med apple silicon. Pt. betyr det at alle java-pakker, til dels tunge, kjører på amd64-emulering.

#127 synes antyde at man uansett må bytte java-base, i den sammenhengen hadde det vært kjekt om man også sørget for at java-interpreteren kan kjøre på aarch64/amd64

Si ifra på Slack om dere ønsker noen med M1-mac til å teste. :) Om det er klart hvilken alternativ java-base man migrerer til, kan jeg teste selv.

**Comment by toresbe** [comment]
Har testet denne i makefile, og den gav meg ihvertfall lokalt en native java som funker

```makefile
# Avoid AMD64 emulation on Apple silicon macs
$(java_arm8_targets): java-%: common java/Dockerfile
       docker pull --platform linux/arm64 openjdk:$(*)-slim
       docker build --platform linux/arm64 -t navikt/java:$(*) --build-arg base_image=openjdk:$(*)-slim java
       docker build --platform linux/arm64 -t navikt/java:$(*)-appdynamics --build-arg base_image=openjdk:$(*)-slim java/appdynamics
```

**Comment by mortenlj** [comment]
Er du sikker? For disse imagene bruker java-common, og den laster ned dumb-init for amd64. Tror du får en slags blandingsimage hvor noe er amd64 og noe er arm64 ... som sikkert funker på mac som emulerer ved behov, men ikke oppleves som en god ting. Dessuten vil kommandoen slik du gjør det overskrive amd64 imagene med arm64 images. Ikke noe vi vil at skal pushes ...

Jeg begynte på å endre til å bygge multiarch images, men akkurat det med dumb-init gjorde at det ble veldig knotete uten å gjøre større endringer, og siden det ikke var det jeg hadde tenkt å drive med denne uken så la jeg det vekk igjen.

Foreslår at de som har dette behovet setter seg ned og gjør det skikkelig (og da kan man gjøre det for alle images, ikke bare java). For å bygge multiarch er det bare å oppgi `--platform` flere ganger, og ta hensyn til dette i de forskjellige `Dockerfiles`.

**Comment by mrsladek** [comment]
Har laget denne her https://github.com/navikt/baseimages/pull/143. Tror java-common er ikke en stor issue her siden `/init-dumb` er skikkelig liten og fungerer ganske bra under emulering og det holder hvis man skal kjøre opp appene lokalt, evtl kan man gjøre noe scripting til å fikse Dockerfile men tror kostnaden blir mye større en det er nyttig.
