### ISSUE TITLE
Kollisjoner ved import av Vault-credentials

### ISSUE THREAD

**Issue by eirslett** [navikt/baseimages#40]
Hvis en applikasjon f.eks. kobler seg til to databaser;

```
oracle/prod/database1.properties
USERNAME=foo
PASSWORD=foo

oracle/prod/database2.properties
USERNAME=bar
PASSWORD=bar
```

Her vil miljøvariablene `USERNAME` og `PASSWORD` kanskje settes til `bar` - den ene konfigurasjonen overskriver konfigurasjonen til den andre. Dette kunne vi kanskje ha løst ved prefiksing: ORACLE_PROD_DATABASE1_USERNAME og ORACLE_PROD_DATABASE2_USERNAME?
Den løsningen er ikke optimal, fordi det vil bli forskjellige navn på miljøvariablene fra miljø til miljø, og så må det håndteres på et vis.
En annen løsning er å lage en mapping mellom navn på fila og hvilket prefiks den skal ha.

Kanskje det enkleste er å ikke lese inn alle `.env`-filene som miljøvariabler, men _kun_ lese inn "hovedfila" til hver app? Så kan applikasjonene selv lese inn hvis de trenger andre stier?

**Comment by linemos** [comment]
Hva med å lese inn som DATABASE.1_properties_USERNAME og DATABASE.2_properties_USERNAME? Altså uten miljø-stien?

**Comment by eirslett** [comment]
Vi kan vel ta problemet når det oppstår!
