### ISSUE TITLE
Bygging

### ISSUE THREAD

**Issue by jksolbakken** [navikt/baseimages#44]
Tenkte jeg skulle lage en ny versjon av node-express basert på Node 12, men ble litt forvirra over versjoneringsopplegget her. Nyeste tag på Docker Hub er "9-common", men den er det ingen spor av i git tags eller i automated builds-historien. Har 9-common blitt pushet manuelt? Hvis jeg pusher en ny git tag "node-express-12.2.0" vil da imaget automagisk bli tagget med 12.2.0? @linemos

**Comment by Kyrremann** [comment]
Tipper du må høre med @linemos

**Comment by linemos** [comment]
9-coommon er pusha manuelt. En glipp fra min side! Det burde settes opp automated builds, ja, ser ikke ut til at det er gjort på dette imaget.

**Comment by linemos** [comment]
Rettelse, det er satt opp, men tydeligvis da etter de tidligere tagga commitene. Så forstår jeg dette rett blir "node-express-12.2.0" gi imaget taggen 12.2.0

**Comment by jksolbakken** [comment]
Jeg prøver, what could possibly go wrong :)

**Comment by jksolbakken** [comment]
Bygget er grønt, men den ble tagget med "latest" 🤷‍♂

**Comment by jksolbakken** [comment]
Never mind, nå dukka det opp ny tag 12.2.0
