### ISSUE TITLE
Hvorfor bygges alle images på nytt hver dag?

### ISSUE THREAD

**Issue by havstein** [navikt/baseimages#54]
På Travis blir alle images bygget hver dag, og nye images lastes opp til Docker Hub. Uavhengig av om det er endringer i repoet. Dette er vel unødvendig, og kan være forvirrende ved feilsøking ("skyldes denne feilen at jeg har fått et annet parent-image?")

Er det noen grunn til at det bygges daglig?

**Comment by eirslett** [comment]
Sånn jeg har skjønt det, så gjøres det for å få inn de siste sikkerhetspatchene (eller patchene mer generelt) fra base-imagene som brukes for å bygge NAV sine base-images.

Hvis du velger å bruke `latest` som tag på base-imaget til NAV (som de fleste velger å gjøre), så er kostnaden ved å feilsøke problemer pga. feil i base-imaget overført til _deg som utvikler_. Det er en balansegang mellom "praktisk å få sikkerhetspatcher inn automatisk" versus "oops, der snek det seg inn en uventet feil". (Don't shoot the messenger - spør du meg, så skulle vi gjerne ha versjonert base-imagene strengt, og fått utviklere til å bumpe versjoner på egen hånd.)

Du kan alltids velge å bruke hash-en til baseimaget som tag, i stedet for `latest`. Da slipper du problemet med feilsøking av ulike parent-image. Til gjengjeld får du selv ansvaret for å patche denne tag-en jevnlig.

Det skal også sies at det er valgfritt å bruke disse base-imagene, du kan like gjerne lage dine egne, og vedlikeholde dem i stedet.

**Comment by havstein** [comment]
Riktig, det gir jo mening å jevnlig ta inn patches. Heller en feil i ny og ne enn en kjip bumperunde.

`latest`, ja.. Imagene i dette repoet bruker jo tags for å skille mellom varianter av images. Kanskje det hadde vært mindre forvirrende om versjon lå i navnet i stedet for taggen - `navikt/node-express-12.2.0-alpine:latest` i stedet for `navikt/node-express:12.2.0-alpine`.
